apply license gradle plugin
grails/grails-core pull request #13535
Opened 2024-07-04 06:24 UTC by sdelamo

This PR applies the [Gradle License Plugin](https://github.com/hierynomus/license-gradle-plugin). The plugin contributes a gradle task `downloadLicenses` which generates a license report of every dependencies.

The plugin is applied to subprojects and the root project to get an aggregated report.

./gradlew downloadLicenses
open build/reports/license/license-dependency.html

2024-07-04 06:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grails/grails-core?pullRequest=13535) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grails/grails-core?pullRequest=13535) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grails/grails-core?pullRequest=13535) it.</sub>

2024-07-05 10:03 UTC, matrei reviewed
To prevent bloating the root build file, could we extract this to a new file, for example: `gradle/dependency-licenses.gradle`?

2024-07-17 07:02 UTC, sdelamo commented
> To prevent bloating the root build file, could we extract this to a new file, for example: `gradle/dependency-licenses.gradle`?

@matrei I did that in https://github.com/grails/grails-core/pull/13535/commits/9e7b15316cfa3a891850e9de8039ac9dd0698eba

2024-07-19 07:02 UTC, matrei requested changes
Nice, now just one more thing I saw (I'm a bit allergic to complex build files):
As we already have an `allprojects` block in `build.gradle`, we can apply the `gradle/dependency-licenses.gradle` file there, so we don't have to do it in multiple places:
```groovy
allprojects {
    
    apply from: rootProject.layout.projectDirectory.file('gradle/dependency-licenses.gradle')

    ...
}
```

2024-07-19 07:02 UTC, matrei commented on gradle/dependency-licenses.gradle
> +}
Is it allowed to have `buildScript` blocks in included files?
I think, as this is already present in `build.gradle` it is not needed here.

2024-07-19 07:02 UTC, matrei commented on build.gradle
> +apply from: "gradle/dependency-licenses.gradle"
Should the `dependency-licenses.gradle` file be applied here, even though it is also applied on line 623?

2024-07-19 07:02 UTC, matrei commented on build.gradle
> +    apply plugin: 'com.github.hierynomus.license-report'
Should the plugin be applied directly here, even though you extracted the functionality to `dependency-licenses.gradle` file and applied it on line 623?

2024-07-25 10:45 UTC, matrei requested changes

2024-07-25 10:45 UTC, matrei commented on gradle/dependency-licenses.gradle
> +        "org.grails:grails-web-fileupload",
Oh, and `org.grails:grails-web-fileupload` is removed in 7.0.x.

If all we want is to exclude all the subprojects, could we do this instead to not have to maintain the list:
```groovy
// We don't want to include any of the libraries from this repo in the license report
List<String> licenseExclusions = rootProject.subprojects.collect {
    "org.grails:${it.name}:${rootProject.projectVersion}" as String
}
```

and we probably want to be able to verify the list:

```groovy
tasks.register('printLicenseExclusions') {
    group = 'license'
    description = 'Prints the license exclusions list'
    doLast {
        println """
            |============================================================
            |The following projects are excluded from the license report:
            |============================================================
            |${licenseExclusions.join('\n')}
        """.stripMargin()
    }
}
```

2024-07-25 19:31 UTC, matrei commented
@sdelamo Sorry, for the delay in reviewing, I had not fully understood the process so my comments were left in pending state.

2024-08-16 21:28 UTC, matrei approved these changes

2024-08-20 18:16 UTC, merged