add trimToNull method on GrailsStringUtils
grails/grails-core pull request #13807
Opened 2024-10-23 20:19 UTC by jamesfredley

2024-10-23 20:36 UTC, codeconsole requested changes, later dismissed
Thanks, I was going to do this, but I would also like a comment that references commons-lang and the version it was taken from and even a permalink to the public repo.  

Although it might not be critical for this method, there is a need to bring some other methods over and it is best they keep in sync with the original repo.  

In the end, I want to search for "commons-lang" or "commons-text" and easily find this method.   This probably should actually be referenced to commons-text if it was moved there.

2024-10-23 20:42 UTC, jamesfredley commented
Ok, make any changes you would like.

This method does the same thing, but the implementation is different, utilizing org.springframework.util.StringUtils.hasLength()

2024-10-23 20:49 UTC, codeconsole commented
ok, thanks, still would be useful.  It's too bad commons-text depends on commons-lang3.  If the 2 dependencies didn't take up so much disk space, I would support keeping them, but I don't see the few methods that we actually use warranting the amount of disk space.

2024-10-28 19:23 UTC, jeffscottbrown commented
> This method does the same thing, but the implementation is different, utilizing org.springframework.util.StringUtils.hasLength()

Do you know if the commons-lang method has test coverage for any surprising cases (don't know what they might be)?

2025-02-28 21:30 UTC, jamesfredley commented
Added test coverage based on 

https://github.com/apache/commons-lang/blob/c8a43a456fb43d2f272a05f3a947bcb9f1719ae8/src/test/java/org/apache/commons/lang3/StringUtilsTrimStripTest.java#L269-L281

2025-03-02 12:05 UTC, matrei approved these changes

2025-03-02 12:05 UTC, matrei commented on grails-core/src/test/groovy/grails/util/GrailsStringUtilsSpec.groovy
> +    }
Can be simplified to:
```groovy
    static final String FOO = 'foo'
    static final String TRIMMABLE
    static final String NON_TRIMMABLE

    static {
        def trimmable = new StringBuilder()
        def nonTrimmable = new StringBuilder()
        (0..<Character.MAX_VALUE).each { i ->
            char ch = (char) i
            if (Character.isWhitespace(ch) && i > 32) {
                nonTrimmable.append(ch)
            }
        }
        (0..32).each { int i ->
            trimmable.append((char) i)
        }
        TRIMMABLE = trimmable.toString()
        NON_TRIMMABLE = nonTrimmable.toString()
    }
```

2025-03-03 03:09 UTC, jdaugherty approved these changes

2025-03-03 03:09 UTC, jdaugherty commented on grails-core/src/test/groovy/grails/util/GrailsStringUtilsSpec.groovy
> +    }
Shouldn't we expand the tests to use these other values instead?

2025-03-03 06:28 UTC, matrei commented on grails-core/src/test/groovy/grails/util/GrailsStringUtilsSpec.groovy
> +    }
Are there cases missing? I think `TRIMMABLE` and `NON_TRIMMABLE` covers what we need to test in`trimToNull()` and I don't see a use case for the removed constants in the other tests.

2025-03-03 15:21 UTC, jamesfredley commented on grails-core/src/test/groovy/grails/util/GrailsStringUtilsSpec.groovy
> +    }
Updated to remove unused variables with simplified syntax.  

These may be added back if we directly implement further methods from "commons-lang" or "commons-text".

2025-03-03 16:41 UTC, jdaugherty approved these changes

2025-03-07 14:47 UTC, merged